# Generated by Django 6.0.1 on 2026-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ] # It file shows this file have dependency on 0001_initial file
        # If we delete it directly then database wil collapse

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
