# Generated by Django 6.0.1 on 2026-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_car_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_count',
            field=models.IntegerField(default=1),
        ),
    ]
